const UNIVERSITIES = {
  BATMAN_UNIVERSITY: "Batman University",
  BAHCESEHIR_UNIVERSITY: "Bahçeşehir University",
  GAZI_UNIVERSITY: "Gazi University",
  TED_UNIVERSITY: "TED University",
  FATIH_SULTAN_MEHMET_VAKIF_UNIVERSITY: "Fatih Sultan Mehmet Vakıf University",
  SABANCI_UNIVERSITY: "Sabancı University",
  GALATA_UNIVERSITY: "Galata University",
  NISANTASI_UNIVERSITY: "Nişantaşı University",
  BEYKENT_UNIVERSITY: "Beykent University",
  SULEYMAN_DEMIREL_UNIVERSITY: "Süleyman Demirel University",
  ADIGUZEL_VOCATIONAL_SCHOOL: "Adıgüzel Vocational School",
  BARTIN_UNIVERSITY: "Bartın University (again)",
  MERSIN_UNIVERSITY: "Mersin University",
  BAHCESEHIR_CYPRUS_UNIVERSITY: "Bahçeşehir Cyprus University",
  EGE_UNIVERSITY: "Ege University",
  ISKENDERUN_TECHNICAL_UNIVERSITY: "İskenderun Technical University",
  SELCUK_UNIVERSITY: "Selçuk University",
  AKDENIZ_UNIVERSITY: "Akdeniz University",
  ANKARA_SOCIAL_SCIENCES_UNIVERSITY: "Ankara Social Sciences University",
  DOKUZ_EYLUL_UNIVERSITY: "Dokuz Eylül University",
  ISPARTA_UNIVERSITY_OF_APPLIED_SCIENCES: "Isparta University of Applied Sciences",
  GEBZE_TECHNICAL_UNIVERSITY: "Gebze Technical University",
  TURKISH_GERMAN_UNIVERSITY: "TU (Turkish-German University)",
  OZYEGIN_UNIVERSITY: "Özyeğin University",
  KARAMANOGLU_MEHMETBEY_UNIVERSITY: "Karamanoglu Mehmetbey University",
  FENERBAHCE_UNIVERSITY: "Fenerbahçe University",
  OZYEGIN_UNIVERSITY_2: "Özyeğin University (again)",
  ERZURUM_TECHNICAL_UNIVERSITY: "Erzurum Technical University",
  ISTANBUL_UNIVERSITY: "Istanbul University",
  YILDIZ_TECHNICAL_UNIVERSITY: "Yıldız Technical University",
  ALANYA_ALAADDIN_KEYKUBAT_UNIVERSITY: "Alanya Alaaddin Keykubat University",
  ALANYA_UNIVERSITY: "Alanya University",
  KUTAHYA_HEALTH_SCIENCES_UNIVERSITY: "Kütahya Health Sciences University",
  SAKARYA_UNIVERSITY_OF_APPLIED_SCIENCES: "Sakarya University of Applied Sciences",
  ERCIYES_UNIVERSITY: "Erciyes University",
  ISTANBUL_TICARET_UNIVERSITY: "İstanbul Ticaret University",
  TURK_HAVA_KURUMU_UNIVERSITY: "Türk Hava Kurumu University",
  BINGOL_UNIVERSITY: "Bingol University",
  PIRI_REIS_UNIVERSITY: "Piri Reis University",
  CYPRUS_WEST_UNIVERSITY: "Cyprus West University",
  KIRIKKALE_UNIVERSITY: "Kırıkkale University",
  UNKNOWN_PRIVATE: "Unknown/Private",
  AIR_FORCE_ACADEMY: "Hava Harp Okulu (Air Force Academy)",
  ANADOLU_UNIVERSITY: "Anadolu University",
  ISTANBUL_TECHNICAL_UNIVERSITY: "Istanbul Technical University",
  ADANA_ALPARSLAN_TURKES_UNIVERSITY: "Adana Alparslan Türkeş Science and Technology University",
  ZONGULDAK_BULENT_ECEVIT_UNIVERSITY: "Zonguldak Bulent Ecevit University",
  ISTANBUL_MEDENIYET_UNIVERSITY: "Istanbul Medeniyet University",
  AKSARAY_UNIVERSITY: "Aksaray University",
  ANTALYA_BILIM_UNIVERSITY: "Antalya Bilim University",
  KAHRAMANMARAS_SUTCU_IMAM_UNIVERSITY: "Kahramanmaraş Sütçü İmam University",
  RECEP_TAYYIP_ERDOGAN_UNIVERSITY: "Recep Tayyip Erdogan University",
  MANISA_CELAL_BAYAR_UNIVERSITY: "Manisa Celal Bayar University",
  KASTAMONU_UNIVERSITY: "Kastamonu University",
  MIDDLE_EAST_TECHNICAL_UNIVERSITY: "Middle East Technical University",
  BOGAZICI_UNIVERSITY: "Boğaziçi University",
  GAZIOSMANPASA_UNIVERSITY: "Gaziosmanpasa University",
  BILKENT_UNIVERSITY: "Bilkent University",
  HACETTEPE_UNIVERSITY: "Hacettepe University (Computer Engineering Dept.)",
  YEDITEPE_UNIVERSITY: "Yeditepe University",
  GIRESUN_UNIVERSITY: "Giresun University",
  HASAN_KALYONCU_UNIVERSITY: "Hasan Kalyoncu University",
  HALIC_UNIVERSITY: "Haliç University",
  BILKENT_UNIVERSITY_UNAM: "Bilkent University UNAM (National Nanotechnology Research Center)",
  YOZGAT_BOZOK_UNIVERSITY: "Yozgat Bozok University",
  IZMIR_DEMOKRASI_UNIVERSITY: "İzmir Demokrasi University",
  SIIRT_UNIVERSITY: "Siirt University",
  ALTINBAS_UNIVERSITY: "Altınbaş University",
  ISTANBUL_GEDIK_UNIVERSITY: "İstanbul Gedik University",
  ISTIKLAL_UNIVERSITY: "İstiklal University",
  SAMSUN_UNIVERSITY: "Samsun University",
  GAZIANTEP_UNIVERSITY: "Gaziantep University",
  AFYON_KOCATEPE_UNIVERSITY: "Afyon Kocatepe University",
  NATIONAL_DEFENCE_UNIVERSITY: "National Defence University",
  ADANA_ALPARSLAN_TURKES_UNIVERSITY: "Adana Alparslan Türkeş Science and Technology University",
  ADNAN_MENDERES_UNIVERSITY: "Adnan Menderes University",
  IZMIR_INSTITUTE_OF_TECHNOLOGY: "Izmir Institute of Technology",
  SAKARYA_UNIVERSITY: "Sakarya University",
  SAGLIK_BILIMLERI_UNIVERSITY: "Sağlık Bilimleri University",
  ESKISEHIR_OSMANGAZI_UNIVERSITY: "Eskişehir Osmangazi University",
  USAK_UNIVERSITY: "Uşak University",
  KARADENIZ_TECHNICAL_UNIVERSITY: "Karadeniz Technical University",
  MIMAR_SINAN_FINE_ARTS_UNIVERSITY: "Mimar Sinan Fine Arts University",
  OSMANIYE_KORKUT_ATA_UNIVERSITY: "Osmaniye Korkut Ata University",
  BASKENT_UNIVERSITY: "Başkent University",
  NEVSEHIR_HACI_BEKTAS_VELI_UNIVERSITY: "Nevşehir Hacı Bektaş Veli University",
  GAZIANTEP_ISLAM_BILIM_TEKNOLOJI_UNIVERSITY: "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
  SIRNAK_UNIVERSITY: "Şırnak University",
  ERZINCAN_BINALI_YILDIRIM_UNIVERSITY: "Erzincan Binali Yildirim University",
  HACI_BAYRAM_VELI_UNIVERSITY: "Hacı Bayram Veli University",
  ORDU_UNIVERSITY: "Ordu University",
  ANKARA_UNIVERSITY: "Ankara University",
  KADIR_HAS_UNIVERSITY: "Kadir Has University",
  YILDIZ_TECHNICAL_UNIVERSITY: "Yildiz Technical University",
  GUMUSHANE_UNIVERSITY: "Gümüşhane University",
  CANKIRI_KARATEKIN_UNIVERSITY: "Çankırı Karatekin University",
  KONYA_FOOD_AGRICULTURE_UNIVERSITY: "Konya Food and Agriculture University",
  DICLE_UNIVERSITY: "Dicle University",
  ADIYAMAN_UNIVERSITY: "Adıyaman University",
  FIRAT_UNIVERSITY: "Firat University",
  NEAR_EAST_UNIVERSITY: "Near East University",
  BOZOK_UNIVERSITY: "Bozok University",
  TOROS_UNIVERSITY: "Toros University",
  UNIVERSITY_OF_KYRENIA: "University of Kyrenia",
  TRAKYA_UNIVERSITY: "Trakya University",
  MUS_ALPARSLAN_UNIVERSITY: "Muş Alparslan University",
  MARMARA_UNIVERSITY: "Marmara University",
  AMASYA_UNIVERSITY: "Amasya University",
  BITLIS_EREN_UNIVERSITY: "Bitlis Eren University",
  MALTEPE_UNIVERSITY: "Maltepe University",
  KILIS_7_ARALIK_UNIVERSITY: "Kilis 7 Aralık University",
  YASAR_UNIVERSITY: "Yasar University",
  ISTANBUL_BILGI_UNIVERSITY: "İstanbul Bilgi University",
  IGDIR_UNIVERSITY: "Iğdır University",
  MUSTAFA_KEMAL_UNIVERSITY: "Mustafa Kemal University",
  ISTANBUL_SAGLIK_TEKNOLOJI_UNIVERSITY: "İstanbul Sağlık ve Teknoloji Üniversitesi (ISTUN)",
  ISTANBUL_ATLAS_UNIVERSITY: "Istanbul Atlas University",
  PAMUKKALE_UNIVERSITY: "Pamukkale University",
  KAYSERI_UNIVERSITY: "Kayseri University",
  ISTANBUL_ESENYURT_UNIVERSITY: "İstanbul Esenyurt University",
  ISTANBUL_UNIVERSITY_CERRAHPASA: "Istanbul University-Cerrahpasa",
  NAMIK_KEMAL_UNIVERSITY: "Namık Kemal University",
  BIRUNI_UNIVERSITY: "Biruni University",
  IZMIR_UNIVERSITY_OF_ECONOMICS: "İzmir University of Economics",
  KENT_UNIVERSITY: "Kent University",
  DUZCE_UNIVERSITY: "Duzce University",
  MARDIN_ARTUKLU_UNIVERSITY: "Mardin Artuklu University",
  BELEK_UNIVERSITY: "Belek University",
  IZMIR_BAKIRCAY_UNIVERSITY: "İzmir Bakırçay University",
  KOCAELI_SAGLIK_TEKNOLOJI_UNIVERSITY: "Kocaeli Sağlık ve Teknoloji University",
  YEDITEPE_UNIVERSITY: "Yeditepe University",
  MUGLA_SITKI_KOCMAN_UNIVERSITY: "Mugla Sitki Kocman University",
  DOGUS_UNIVERSITY: "Doğuş University",
  ATILIM_UNIVERSITY: "Atılım University",
  OKAN_UNIVERSITY: "Okan University",
  ISTANBUL_AYDIN_UNIVERSITY: "İstanbul Aydın University",
  RUMELI_UNIVERSITY: "Rumeli University",
  KIRSEHIR_AHI_EVRAN_UNIVERSITY: "Kırşehir Ahi Evran University",
  OSTIM_TECHNICAL_UNIVERSITY: "OSTİM Technical University",
  CYPRUS_SCIENCE_UNIVERSITY: "Cyprus Science University",
  NATIONAL_DEFENCE_UNIVERSITY_NAVAL_ACADEMY: "National Defence University (Naval Academy)",
  MIDDLE_EAST_TECHNICAL_UNIVERSITY_INSTITUTE: "Middle East Technical University (Institute)",
  ISTINYE_UNIVERSITY: "Istinye University",
  ARTVIN_CORUH_UNIVERSITY: "Artvin Coruh University",
  ATATURK_UNIVERSITY: "Ataturk Universitesi",
  NIGDE_OMER_HALISDEMIR_UNIVERSITY: "Niğde Ömer Halisdemir University",
  KAFKAS_UNIVERSITY: "Kafkas University",
  KAPADOKYA_UNIVERSITY: "Kapadokya University",
  KARA_HARP_OKULU: "Kara Harp Okulu",
  CELAL_BAYAR_UNIVERSITY: "Celal Bayar University",
  ISTANBUL_GELISIM_UNIVERSITY: "İstanbul Gelişim University",
  YALOVA_UNIVERSITY: "Yalova University",
  BALIKESIR_UNIVERSITY: "Balikesir University",
  BAYBURT_UNIVERSITY: "Bayburt University",
  ONDOKUZ_MAYIS_UNIVERSITY: "Ondokuz Mayis University",
  INONU_UNIVERSITY: "İnönü University",
  ISTANBUL_AYVANSARAY_UNIVERSITY: "Istanbul Ayvansaray University",
  CUKUROVA_UNIVERSITY: "Çukurova University",
  TARSUS_UNIVERSITY: "Tarsus University",
  MALATYA_TURGUT_OZAL_UNIVERSITY: "Malatya Turgut Özal University",
  ACIBADEM_UNIVERSITY: "Acıbadem University",
  AVRASYA_UNIVERSITY: "Avrasya University",
  IBN_HALDUN_UNIVERSITY: "Ibn Haldun University",
  KTO_KARATAY_UNIVERSITY: "KTO Karatay University",
  KONYA_TECHNICAL_UNIVERSITY: "Konya Technical University",
  HAKKARI_UNIVERSITY: "Hakkari University",
  ISTANBUL_AREL_UNIVERSITY: "İstanbul Arel University",
  ISIK_UNIVERSITY: "Işık University",
  AGRI_IBRAHIM_CECEN_UNIVERSITY: "Ağrı İbrahim Çeçen University",
  BURSA_TECHNICAL_UNIVERSITY: "Bursa Technical University",
  ISTANBUL_YENI_YUZYIL_UNIVERSITY: "Istanbul Yeni Yüzyıl University",
  EASTERN_MEDITERRANEAN_UNIVERSITY: "Eastern Mediterranean University",
  AFYONKARAHISAR_HEALTH_SCIENCES_UNIVERSITY: "Afyonkarahisar Health Sciences University",
  BILECIK_SEYH_EDEBALI_UNIVERSITY: "Bilecik Seyh Edebali University",
  DENIZ_HARP_OKULU: "Deniz Harp Okulu (Naval Academy)",
  NECMETTIN_ERBAKAN_UNIVERSITY: "Necmettin Erbakan University",
  KARABUK_UNIVERSITY: "Karabuk University",
  ESKISEHIR_TECHNICAL_UNIVERSITY: "Eskişehir Technical University",
  ABDULLAH_GUL_UNIVERSITY: "Abdullah Gül University",
  DOKUZ_EYLUL_UNIVERSITY: "Dokuz Eylul University",
  IZMIR_KATIP_CELEBI_UNIVERSITY: "Izmir Katip Celebi University",
  ARDAHAN_UNIVERSITY: "Ardahan University",
  ANKARA_UNIVERSITY_AGRICULTURAL: "Ankara University (Agricultural)",
  BARTIN_UNIVERSITY: "Bartın University",
  KAVRAM_VOCATIONAL_SCHOOL: "Kavram Vocational School",
  TURKISH_GERMAN_UNIVERSITY: "Turkish-German University",
  HACETTEPE_UNIVERSITY: "Hacettepe University",
  KIRKLARELI_UNIVERSITY: "Kırklareli University",
  ANKARA_BILIM_UNIVERSITY: "Ankara Bilim University",
  KOCAELI_UNIVERSITY: "Kocaeli University",
  GALATASARAY_UNIVERSITY: "Galatasaray University",
  NUH_NACI_YAZGAN_UNIVERSITY: "Nuh Naci Yazgan University",
  HARRAN_UNIVERSITY: "Harran University",
  MUDANYA_UNIVERSITY: "Mudanya University",
  EUROPEAN_UNIVERSITY_OF_LEFKE: "European University of Lefke",
  VAN_YUZUNCU_YIL_UNIVERSITY: "Van Yuzuncu Yil University",
  ISTANBUL_TOPKAPI_UNIVERSITY: "Istanbul Topkapı University",
  ARKIN_UNIVERSITY: "Arkin University of Creative Arts and Design",
  CYPRUS_INTERNATIONAL_UNIVERSITY: "Cyprus International University",
  ISTANBUL_SEHIR_UNIVERSITY: "Istanbul Şehir University",
  IZMIR_UNIVERSITY_OF_ECONOMICS: "Izmir University of Economics",
  FINAL_INTERNATIONAL_UNIVERSITY: "Final International University",
  KOC_UNIVERSITY: "Koç University",
  ANKARA_MEDIPOL_UNIVERSITY: "Ankara Medipol University",
  USKUDAR_UNIVERSITY: "Üsküdar University",
  SIVAS_CUMHURIYET_UNIVERSITY: "Sivas Cumhuriyet University",
  SINOP_UNIVERSITY: "Sinop University",
  GAZIANTEP_UNIVERSITY: "Gaziantep University",
  CANAKKALE_ONSEKIZ_MART_UNIVERSITY: "Çanakkale Onsekiz Mart University",
  CANKAYA_UNIVERSITY: "Çankaya University",
  ISTANBUL_MEDIPOL_UNIVERSITY: "İstanbul Medipol University",
  ULUDAG_UNIVERSITY: "Uludağ University",
  MUNZUR_UNIVERSITY: "Munzur University",
  HITIT_UNIVERSITY: "Hitit University",
  BEYKOZ_UNIVERSITY: "Beykoz University",
  TOBB_UNIVERSITY: "TOBB University of Economics and Technology",
  ANKARA_YILDIRIM_BEYAZIT_UNIVERSITY: "Ankara Yildirim Beyazit University",
  TRABZON_UNIVERSITY: "Trabzon University",
  CUKUROVA_UNIVERSITY: "Cukurova University",
  MEF_UNIVERSITY: "MEF University",
  GIRNE_AMERICAN_UNIVERSITY: "Girne American University",
  BANDIRMA_ONYEDI_EYLUL_UNIVERSITY: "Bandirma Onyedi Eylul University",
  KUTAHYA_DUMLUPINAR_UNIVERSITY: "Kütahya Dumlupınar University",
  MEHMET_AKIF_ERSOY_UNIVERSITY: "Mehmet Akif Ersoy University",
  ONDOKUZ_MAYIS_UNIVERSITY: "Ondokuz Mayıs University",
  ISTANBUL_SABAHATTIN_ZAIM_UNIVERSITY: "Istanbul Sabahattin Zaim University"
}

module.exports = UNIVERSITIES